format_version: '2.0'

input_files: 'editorconfig-core-c.i'

properties:
  - property_file: ../properties/valid-memsafety.prp
    expected_verdict: false
  - property_file: ../properties/no-overflow.prp
    expected_verdict: false

options:
  language: C
  data_model: ILP32
  