# This file is part of the SV-Benchmarks collection of verification tasks:
# https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
#
# SPDX-FileCopyrightText: 2025 Roman Amjaga <raltvein@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

LEVEL := ../

include $(LEVEL)/Makefile.config
